[2023-04-09 06:07:06,177: INFO/MainProcess] Connected to redis://localhost:6379//
[2023-04-09 06:07:06,186: INFO/MainProcess] mingle: searching for neighbors
[2023-04-09 06:07:07,219: INFO/MainProcess] mingle: all alone
[2023-04-09 06:07:07,277: WARNING/MainProcess] /Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2023-04-09 06:07:07,278: INFO/MainProcess] celery@Shivas-MacBook-Pro.local ready.
[2023-04-09 06:36:03,228: INFO/MainProcess] Task send_reminder_message[d076b144-70db-468b-8512-76a164fa94be] received
[2023-04-09 06:36:03,592: INFO/ForkPoolWorker-8] -- BEGIN Twilio API Request --
[2023-04-09 06:36:03,598: INFO/ForkPoolWorker-8] POST Request: https://api.twilio.com/2010-04-01/Accounts/ACde7d6fe919f6bfe9030fbca845f4087b/Messages.json
[2023-04-09 06:36:03,599: INFO/ForkPoolWorker-8] Headers:
[2023-04-09 06:36:03,599: INFO/ForkPoolWorker-8] User-Agent : twilio-python/8.0.0 (Darwin x86_64) Python/3.10.9
[2023-04-09 06:36:03,599: INFO/ForkPoolWorker-8] X-Twilio-Client : python-8.0.0
[2023-04-09 06:36:03,599: INFO/ForkPoolWorker-8] Accept-Charset : utf-8
[2023-04-09 06:36:03,600: INFO/ForkPoolWorker-8] Content-Type : application/x-www-form-urlencoded
[2023-04-09 06:36:03,600: INFO/ForkPoolWorker-8] Accept : application/json
[2023-04-09 06:36:03,603: INFO/ForkPoolWorker-8] -- END Twilio API Request --
[2023-04-09 06:36:03,936: INFO/ForkPoolWorker-8] Response Status Code: 201
[2023-04-09 06:36:03,937: INFO/ForkPoolWorker-8] Response Headers: {'Date': 'Sun, 09 Apr 2023 06:36:03 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '913', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQc4ea2482c07d534591fbcd01dba75556', 'Twilio-Request-Duration': '0.099', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
[2023-04-09 06:36:03,958: INFO/ForkPoolWorker-8] Task send_reminder_message[d076b144-70db-468b-8512-76a164fa94be] succeeded in 0.6181067599682137s: None
[2023-04-09 06:37:02,859: INFO/MainProcess] Task send_reminder_message[ec5223b4-6011-4d34-9d2e-fb54e0f07cbc] received
[2023-04-09 06:37:02,864: INFO/ForkPoolWorker-8] -- BEGIN Twilio API Request --
[2023-04-09 06:37:02,864: INFO/ForkPoolWorker-8] POST Request: https://api.twilio.com/2010-04-01/Accounts/ACde7d6fe919f6bfe9030fbca845f4087b/Messages.json
[2023-04-09 06:37:02,865: INFO/ForkPoolWorker-8] Headers:
[2023-04-09 06:37:02,865: INFO/ForkPoolWorker-8] User-Agent : twilio-python/8.0.0 (Darwin x86_64) Python/3.10.9
[2023-04-09 06:37:02,865: INFO/ForkPoolWorker-8] X-Twilio-Client : python-8.0.0
[2023-04-09 06:37:02,865: INFO/ForkPoolWorker-8] Accept-Charset : utf-8
[2023-04-09 06:37:02,866: INFO/ForkPoolWorker-8] Content-Type : application/x-www-form-urlencoded
[2023-04-09 06:37:02,866: INFO/ForkPoolWorker-8] Accept : application/json
[2023-04-09 06:37:02,866: INFO/ForkPoolWorker-8] -- END Twilio API Request --
[2023-04-09 06:37:02,974: INFO/ForkPoolWorker-8] Response Status Code: 201
[2023-04-09 06:37:02,974: INFO/ForkPoolWorker-8] Response Headers: {'Date': 'Sun, 09 Apr 2023 06:37:03 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '913', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQ13491489972faa8c6336c8c791a6ecf7', 'Twilio-Request-Duration': '0.082', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
[2023-04-09 06:37:02,980: INFO/ForkPoolWorker-8] Task send_reminder_message[ec5223b4-6011-4d34-9d2e-fb54e0f07cbc] succeeded in 0.11707361601293087s: None
[2023-04-23 05:46:43,176: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2023-04-23 05:46:45,187: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2023-04-23 05:46:49,200: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2023-04-23 05:46:55,250: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 8.00 seconds... (4/100)

[2023-04-23 05:47:03,276: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 10.00 seconds... (5/100)

[2023-04-23 05:47:13,325: INFO/MainProcess] Connected to redis://localhost:6379//
[2023-04-23 05:47:13,335: INFO/MainProcess] mingle: searching for neighbors
[2023-04-23 05:47:14,364: INFO/MainProcess] mingle: all alone
[2023-04-23 05:47:14,415: WARNING/MainProcess] /Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2023-04-23 05:47:14,416: INFO/MainProcess] celery@Shivas-MacBook-Pro.local ready.
[2023-04-23 05:47:14,590: INFO/MainProcess] Task send_reminder_message[1c349759-dd19-451d-8f15-e048de12fbb8] received
[2023-04-23 05:47:14,659: INFO/MainProcess] Task send_reminder_message[604eb93f-091a-4a5b-a024-1d33a59188e6] received
[2023-04-23 05:47:14,740: INFO/ForkPoolWorker-4] -- BEGIN Twilio API Request --
[2023-04-23 05:47:14,741: INFO/ForkPoolWorker-4] POST Request: https://api.twilio.com/2010-04-01/Accounts/ACde7d6fe919f6bfe9030fbca845f4087b/Messages.json
[2023-04-23 05:47:14,741: INFO/ForkPoolWorker-4] Headers:
[2023-04-23 05:47:14,742: INFO/ForkPoolWorker-4] User-Agent : twilio-python/8.0.0 (Darwin x86_64) Python/3.10.9
[2023-04-23 05:47:14,742: INFO/ForkPoolWorker-4] X-Twilio-Client : python-8.0.0
[2023-04-23 05:47:14,742: INFO/ForkPoolWorker-4] Accept-Charset : utf-8
[2023-04-23 05:47:14,742: INFO/ForkPoolWorker-4] Content-Type : application/x-www-form-urlencoded
[2023-04-23 05:47:14,743: INFO/ForkPoolWorker-4] Accept : application/json
[2023-04-23 05:47:14,743: INFO/ForkPoolWorker-4] -- END Twilio API Request --
[2023-04-23 05:47:14,754: INFO/ForkPoolWorker-2] -- BEGIN Twilio API Request --
[2023-04-23 05:47:14,755: INFO/ForkPoolWorker-2] POST Request: https://api.twilio.com/2010-04-01/Accounts/ACde7d6fe919f6bfe9030fbca845f4087b/Messages.json
[2023-04-23 05:47:14,755: INFO/ForkPoolWorker-2] Headers:
[2023-04-23 05:47:14,755: INFO/ForkPoolWorker-2] User-Agent : twilio-python/8.0.0 (Darwin x86_64) Python/3.10.9
[2023-04-23 05:47:14,756: INFO/ForkPoolWorker-2] X-Twilio-Client : python-8.0.0
[2023-04-23 05:47:14,756: INFO/ForkPoolWorker-2] Accept-Charset : utf-8
[2023-04-23 05:47:14,756: INFO/ForkPoolWorker-2] Content-Type : application/x-www-form-urlencoded
[2023-04-23 05:47:14,756: INFO/ForkPoolWorker-2] Accept : application/json
[2023-04-23 05:47:14,757: INFO/ForkPoolWorker-2] -- END Twilio API Request --
[2023-04-23 05:47:14,979: INFO/ForkPoolWorker-2] Response Status Code: 201
[2023-04-23 05:47:14,980: INFO/ForkPoolWorker-2] Response Headers: {'Date': 'Sun, 23 Apr 2023 05:47:15 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '910', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQafc22b007ee6527d9bf03c84c5f458e7', 'Twilio-Request-Duration': '0.096', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '2', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
[2023-04-23 05:47:14,984: INFO/ForkPoolWorker-4] Response Status Code: 201
[2023-04-23 05:47:14,985: INFO/ForkPoolWorker-4] Response Headers: {'Date': 'Sun, 23 Apr 2023 05:47:15 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '913', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQ9a5b16cb514ec03209fd1046b0f4d6e8', 'Twilio-Request-Duration': '0.104', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
[2023-04-23 05:47:14,994: INFO/ForkPoolWorker-2] Task send_reminder_message[604eb93f-091a-4a5b-a024-1d33a59188e6] succeeded in 0.32880709299934097s: None
[2023-04-23 05:47:14,997: INFO/ForkPoolWorker-4] Task send_reminder_message[1c349759-dd19-451d-8f15-e048de12fbb8] succeeded in 0.40134725702228025s: None
[2023-04-23 05:47:15,198: INFO/MainProcess] Connected to redis://localhost:6379//
[2023-04-23 05:47:15,208: INFO/MainProcess] mingle: searching for neighbors
[2023-04-23 05:47:16,239: INFO/MainProcess] mingle: all alone
[2023-04-23 05:47:16,281: WARNING/MainProcess] /Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2023-04-23 05:47:16,281: INFO/MainProcess] celery@Shivas-MacBook-Pro.local ready.
[2023-04-23 05:48:14,546: INFO/MainProcess] Task send_reminder_message[f06ed634-fa18-49c8-bbcd-49a01ad0facb] received
[2023-04-23 05:48:14,669: INFO/ForkPoolWorker-4] -- BEGIN Twilio API Request --
[2023-04-23 05:48:14,671: INFO/ForkPoolWorker-4] POST Request: https://api.twilio.com/2010-04-01/Accounts/ACde7d6fe919f6bfe9030fbca845f4087b/Messages.json
[2023-04-23 05:48:14,671: INFO/ForkPoolWorker-4] Headers:
[2023-04-23 05:48:14,672: INFO/ForkPoolWorker-4] User-Agent : twilio-python/8.0.0 (Darwin x86_64) Python/3.10.9
[2023-04-23 05:48:14,672: INFO/ForkPoolWorker-4] X-Twilio-Client : python-8.0.0
[2023-04-23 05:48:14,673: INFO/ForkPoolWorker-4] Accept-Charset : utf-8
[2023-04-23 05:48:14,673: INFO/ForkPoolWorker-4] Content-Type : application/x-www-form-urlencoded
[2023-04-23 05:48:14,673: INFO/ForkPoolWorker-4] Accept : application/json
[2023-04-23 05:48:14,673: INFO/ForkPoolWorker-4] -- END Twilio API Request --
[2023-04-23 05:48:14,676: INFO/MainProcess] Task send_reminder_message[8776c97d-36d4-46de-8d28-98ac6e3b11d2] received
[2023-04-23 05:48:14,700: INFO/ForkPoolWorker-4] -- BEGIN Twilio API Request --
[2023-04-23 05:48:14,705: INFO/ForkPoolWorker-4] POST Request: https://api.twilio.com/2010-04-01/Accounts/ACde7d6fe919f6bfe9030fbca845f4087b/Messages.json
[2023-04-23 05:48:14,706: INFO/ForkPoolWorker-4] Headers:
[2023-04-23 05:48:14,706: INFO/ForkPoolWorker-4] User-Agent : twilio-python/8.0.0 (Darwin x86_64) Python/3.10.9
[2023-04-23 05:48:14,707: INFO/ForkPoolWorker-4] X-Twilio-Client : python-8.0.0
[2023-04-23 05:48:14,707: INFO/ForkPoolWorker-4] Accept-Charset : utf-8
[2023-04-23 05:48:14,708: INFO/ForkPoolWorker-4] Content-Type : application/x-www-form-urlencoded
[2023-04-23 05:48:14,708: INFO/ForkPoolWorker-4] Accept : application/json
[2023-04-23 05:48:14,709: INFO/ForkPoolWorker-4] -- END Twilio API Request --
[2023-04-23 05:48:14,848: INFO/ForkPoolWorker-4] Response Status Code: 201
[2023-04-23 05:48:14,849: INFO/ForkPoolWorker-4] Response Headers: {'Date': 'Sun, 23 Apr 2023 05:48:14 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '910', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQ05c682ae548343837f745200ada744ef', 'Twilio-Request-Duration': '0.098', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
[2023-04-23 05:48:14,861: INFO/ForkPoolWorker-4] Task send_reminder_message[8776c97d-36d4-46de-8d28-98ac6e3b11d2] succeeded in 0.17629136200412177s: None
[2023-04-23 05:48:14,901: INFO/ForkPoolWorker-4] Response Status Code: 201
[2023-04-23 05:48:14,901: INFO/ForkPoolWorker-4] Response Headers: {'Date': 'Sun, 23 Apr 2023 05:48:14 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '913', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQea49e6b9c1c3788eecb5cc17249738c6', 'Twilio-Request-Duration': '0.099', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '2', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
[2023-04-23 05:48:14,915: INFO/ForkPoolWorker-4] Task send_reminder_message[f06ed634-fa18-49c8-bbcd-49a01ad0facb] succeeded in 0.3609170760028064s: None
[2023-04-23 05:49:14,553: INFO/MainProcess] Task send_reminder_message[ecb0d380-b58c-4489-890e-1f2102eaeb05] received
[2023-04-23 05:49:14,556: INFO/ForkPoolWorker-4] -- BEGIN Twilio API Request --
[2023-04-23 05:49:14,556: INFO/ForkPoolWorker-4] POST Request: https://api.twilio.com/2010-04-01/Accounts/ACde7d6fe919f6bfe9030fbca845f4087b/Messages.json
[2023-04-23 05:49:14,557: INFO/ForkPoolWorker-4] Headers:
[2023-04-23 05:49:14,557: INFO/ForkPoolWorker-4] User-Agent : twilio-python/8.0.0 (Darwin x86_64) Python/3.10.9
[2023-04-23 05:49:14,557: INFO/ForkPoolWorker-4] X-Twilio-Client : python-8.0.0
[2023-04-23 05:49:14,558: INFO/ForkPoolWorker-4] Accept-Charset : utf-8
[2023-04-23 05:49:14,558: INFO/ForkPoolWorker-4] Content-Type : application/x-www-form-urlencoded
[2023-04-23 05:49:14,558: INFO/ForkPoolWorker-4] Accept : application/json
[2023-04-23 05:49:14,558: INFO/ForkPoolWorker-4] -- END Twilio API Request --
[2023-04-23 05:49:14,676: INFO/ForkPoolWorker-4] Response Status Code: 201
[2023-04-23 05:49:14,676: INFO/ForkPoolWorker-4] Response Headers: {'Date': 'Sun, 23 Apr 2023 05:49:14 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '913', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQbe199f3c494dd1ff1d94bdb161bbb9ca', 'Twilio-Request-Duration': '0.088', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
[2023-04-23 05:49:14,682: INFO/ForkPoolWorker-4] Task send_reminder_message[ecb0d380-b58c-4489-890e-1f2102eaeb05] succeeded in 0.1270391000143718s: None
[2023-04-23 05:49:14,692: INFO/MainProcess] Task send_reminder_message[4c61f094-964d-4f64-bb2f-9c7cd3643e0a] received
[2023-04-23 05:49:14,693: INFO/ForkPoolWorker-4] -- BEGIN Twilio API Request --
[2023-04-23 05:49:14,693: INFO/ForkPoolWorker-4] POST Request: https://api.twilio.com/2010-04-01/Accounts/ACde7d6fe919f6bfe9030fbca845f4087b/Messages.json
[2023-04-23 05:49:14,694: INFO/ForkPoolWorker-4] Headers:
[2023-04-23 05:49:14,694: INFO/ForkPoolWorker-4] User-Agent : twilio-python/8.0.0 (Darwin x86_64) Python/3.10.9
[2023-04-23 05:49:14,695: INFO/ForkPoolWorker-4] X-Twilio-Client : python-8.0.0
[2023-04-23 05:49:14,695: INFO/ForkPoolWorker-4] Accept-Charset : utf-8
[2023-04-23 05:49:14,695: INFO/ForkPoolWorker-4] Content-Type : application/x-www-form-urlencoded
[2023-04-23 05:49:14,695: INFO/ForkPoolWorker-4] Accept : application/json
[2023-04-23 05:49:14,696: INFO/ForkPoolWorker-4] -- END Twilio API Request --
[2023-04-23 05:49:14,810: INFO/ForkPoolWorker-4] Response Status Code: 201
[2023-04-23 05:49:14,810: INFO/ForkPoolWorker-4] Response Headers: {'Date': 'Sun, 23 Apr 2023 05:49:14 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '910', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQ64d0ffed663b4a953d562e73afebbd57', 'Twilio-Request-Duration': '0.093', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
[2023-04-23 05:49:14,816: INFO/ForkPoolWorker-4] Task send_reminder_message[4c61f094-964d-4f64-bb2f-9c7cd3643e0a] succeeded in 0.1232961859786883s: None
[2023-04-23 05:49:29,933: INFO/MainProcess] Task send_reminder_message[2f3c7dab-dd61-4652-8e87-4aeeae7dd01e] received
[2023-04-23 05:49:29,935: INFO/ForkPoolWorker-4] -- BEGIN Twilio API Request --
[2023-04-23 05:49:29,936: INFO/ForkPoolWorker-4] POST Request: https://api.twilio.com/2010-04-01/Accounts/ACde7d6fe919f6bfe9030fbca845f4087b/Messages.json
[2023-04-23 05:49:29,936: INFO/ForkPoolWorker-4] Headers:
[2023-04-23 05:49:29,936: INFO/ForkPoolWorker-4] User-Agent : twilio-python/8.0.0 (Darwin x86_64) Python/3.10.9
[2023-04-23 05:49:29,937: INFO/ForkPoolWorker-4] X-Twilio-Client : python-8.0.0
[2023-04-23 05:49:29,937: INFO/ForkPoolWorker-4] Accept-Charset : utf-8
[2023-04-23 05:49:29,937: INFO/ForkPoolWorker-4] Content-Type : application/x-www-form-urlencoded
[2023-04-23 05:49:29,937: INFO/ForkPoolWorker-4] Accept : application/json
[2023-04-23 05:49:29,938: INFO/ForkPoolWorker-4] -- END Twilio API Request --
[2023-04-23 05:49:30,107: INFO/ForkPoolWorker-4] Response Status Code: 201
[2023-04-23 05:49:30,108: INFO/ForkPoolWorker-4] Response Headers: {'Date': 'Sun, 23 Apr 2023 05:49:30 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '912', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQ4aad0e7d0955047abd4dcae0bea54e3c', 'Twilio-Request-Duration': '0.094', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
[2023-04-23 05:49:30,113: INFO/ForkPoolWorker-4] Task send_reminder_message[2f3c7dab-dd61-4652-8e87-4aeeae7dd01e] succeeded in 0.17825640199589543s: None
[2023-04-23 05:50:14,578: INFO/MainProcess] Task send_reminder_message[3aadad44-35d5-44ed-b87f-3329c49e33b5] received
[2023-04-23 05:50:14,595: INFO/ForkPoolWorker-4] -- BEGIN Twilio API Request --
[2023-04-23 05:50:14,597: INFO/ForkPoolWorker-4] POST Request: https://api.twilio.com/2010-04-01/Accounts/ACde7d6fe919f6bfe9030fbca845f4087b/Messages.json
[2023-04-23 05:50:14,597: INFO/ForkPoolWorker-4] Headers:
[2023-04-23 05:50:14,597: INFO/ForkPoolWorker-4] User-Agent : twilio-python/8.0.0 (Darwin x86_64) Python/3.10.9
[2023-04-23 05:50:14,598: INFO/ForkPoolWorker-4] X-Twilio-Client : python-8.0.0
[2023-04-23 05:50:14,598: INFO/ForkPoolWorker-4] Accept-Charset : utf-8
[2023-04-23 05:50:14,598: INFO/ForkPoolWorker-4] Content-Type : application/x-www-form-urlencoded
[2023-04-23 05:50:14,598: INFO/ForkPoolWorker-4] Accept : application/json
[2023-04-23 05:50:14,599: INFO/ForkPoolWorker-4] -- END Twilio API Request --
[2023-04-23 05:50:14,778: INFO/ForkPoolWorker-4] Response Status Code: 201
[2023-04-23 05:50:14,778: INFO/ForkPoolWorker-4] Response Headers: {'Date': 'Sun, 23 Apr 2023 05:50:14 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '913', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQa6ce14cc15b8769ef218996d0f8215d7', 'Twilio-Request-Duration': '0.088', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
[2023-04-23 05:50:14,791: INFO/ForkPoolWorker-4] Task send_reminder_message[3aadad44-35d5-44ed-b87f-3329c49e33b5] succeeded in 0.20237231301143765s: None
[2023-04-23 05:50:14,820: INFO/MainProcess] Task send_reminder_message[47890387-4d51-494f-b4fb-dc51cd4b8388] received
[2023-04-23 05:50:14,835: INFO/ForkPoolWorker-4] -- BEGIN Twilio API Request --
[2023-04-23 05:50:14,837: INFO/ForkPoolWorker-4] POST Request: https://api.twilio.com/2010-04-01/Accounts/ACde7d6fe919f6bfe9030fbca845f4087b/Messages.json
[2023-04-23 05:50:14,838: INFO/ForkPoolWorker-4] Headers:
[2023-04-23 05:50:14,838: INFO/ForkPoolWorker-4] User-Agent : twilio-python/8.0.0 (Darwin x86_64) Python/3.10.9
[2023-04-23 05:50:14,838: INFO/ForkPoolWorker-4] X-Twilio-Client : python-8.0.0
[2023-04-23 05:50:14,839: INFO/ForkPoolWorker-4] Accept-Charset : utf-8
[2023-04-23 05:50:14,839: INFO/ForkPoolWorker-4] Content-Type : application/x-www-form-urlencoded
[2023-04-23 05:50:14,840: INFO/ForkPoolWorker-4] Accept : application/json
[2023-04-23 05:50:14,840: INFO/ForkPoolWorker-4] -- END Twilio API Request --
[2023-04-23 05:50:15,000: INFO/ForkPoolWorker-4] Response Status Code: 201
[2023-04-23 05:50:15,000: INFO/ForkPoolWorker-4] Response Headers: {'Date': 'Sun, 23 Apr 2023 05:50:15 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '910', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQdfe782f3d9ffba14df8713f3a62b7b90', 'Twilio-Request-Duration': '0.127', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
[2023-04-23 05:50:15,011: INFO/ForkPoolWorker-4] Task send_reminder_message[47890387-4d51-494f-b4fb-dc51cd4b8388] succeeded in 0.1812137830129359s: None
[2023-04-23 05:50:29,938: INFO/MainProcess] Task send_reminder_message[120a3427-a26c-4b62-941e-8fe58998d156] received
[2023-04-23 05:50:29,940: INFO/ForkPoolWorker-4] -- BEGIN Twilio API Request --
[2023-04-23 05:50:29,940: INFO/ForkPoolWorker-4] POST Request: https://api.twilio.com/2010-04-01/Accounts/ACde7d6fe919f6bfe9030fbca845f4087b/Messages.json
[2023-04-23 05:50:29,941: INFO/ForkPoolWorker-4] Headers:
[2023-04-23 05:50:29,941: INFO/ForkPoolWorker-4] User-Agent : twilio-python/8.0.0 (Darwin x86_64) Python/3.10.9
[2023-04-23 05:50:29,941: INFO/ForkPoolWorker-4] X-Twilio-Client : python-8.0.0
[2023-04-23 05:50:29,942: INFO/ForkPoolWorker-4] Accept-Charset : utf-8
[2023-04-23 05:50:29,942: INFO/ForkPoolWorker-4] Content-Type : application/x-www-form-urlencoded
[2023-04-23 05:50:29,942: INFO/ForkPoolWorker-4] Accept : application/json
[2023-04-23 05:50:29,943: INFO/ForkPoolWorker-4] -- END Twilio API Request --
[2023-04-23 05:50:30,057: INFO/ForkPoolWorker-4] Response Status Code: 201
[2023-04-23 05:50:30,058: INFO/ForkPoolWorker-4] Response Headers: {'Date': 'Sun, 23 Apr 2023 05:50:30 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '912', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQ4d65c3625be9b909138fbdb6718420a8', 'Twilio-Request-Duration': '0.093', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
[2023-04-23 05:50:30,063: INFO/ForkPoolWorker-4] Task send_reminder_message[120a3427-a26c-4b62-941e-8fe58998d156] succeeded in 0.12383942399173975s: None
[2023-04-23 05:50:37,712: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 332, in start
    blueprint.start(self)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 628, in start
    c.loop(*c.loop_args())
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/kombu/transport/redis.py", line 1326, in on_readable
    self.cycle.on_readable(fileno)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/kombu/transport/redis.py", line 562, in on_readable
    chan.handlers[type]()
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/kombu/transport/redis.py", line 906, in _receive
    ret.append(self._receive_one(c))
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/kombu/transport/redis.py", line 916, in _receive_one
    response = c.parse_response()
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/client.py", line 1531, in parse_response
    response = self._execute(conn, try_read)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/client.py", line 1507, in _execute
    return conn.retry.call_with_retry(
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/client.py", line 1509, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/client.py", line 1496, in _disconnect_raise_connect
    raise error
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/client.py", line 1508, in <lambda>
    lambda: command(*args, **kwargs),
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/client.py", line 1529, in try_read
    return conn.read_response()
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/connection.py", line 865, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/connection.py", line 346, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/connection.py", line 356, in _read_response
    raw = self._buffer.readline()
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/connection.py", line 259, in readline
    self._read_from_socket()
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/connection.py", line 212, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2023-04-23 05:50:37,710: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 332, in start
    blueprint.start(self)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 628, in start
    c.loop(*c.loop_args())
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/kombu/transport/redis.py", line 1326, in on_readable
    self.cycle.on_readable(fileno)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/kombu/transport/redis.py", line 562, in on_readable
    chan.handlers[type]()
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/kombu/transport/redis.py", line 906, in _receive
    ret.append(self._receive_one(c))
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/kombu/transport/redis.py", line 916, in _receive_one
    response = c.parse_response()
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/client.py", line 1531, in parse_response
    response = self._execute(conn, try_read)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/client.py", line 1507, in _execute
    return conn.retry.call_with_retry(
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/client.py", line 1509, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/client.py", line 1496, in _disconnect_raise_connect
    raise error
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/client.py", line 1508, in <lambda>
    lambda: command(*args, **kwargs),
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/client.py", line 1529, in try_read
    return conn.read_response()
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/connection.py", line 865, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/connection.py", line 346, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/connection.py", line 356, in _read_response
    raw = self._buffer.readline()
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/connection.py", line 259, in readline
    self._read_from_socket()
  File "/Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/redis/connection.py", line 212, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2023-04-23 05:50:37,781: WARNING/MainProcess] /Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:367: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2023-04-23 05:50:37,781: WARNING/MainProcess] /Users/shivamenta/.local/share/virtualenvs/milestone-monitor-U6VeiWHH/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:367: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2023-04-23 05:50:37,808: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Connection closed by server..
Trying again in 2.00 seconds... (1/100)

[2023-04-23 05:50:37,808: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Connection closed by server..
Trying again in 2.00 seconds... (1/100)

[2023-04-23 05:50:39,818: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2023-04-23 05:50:39,818: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2023-04-23 05:50:43,830: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2023-04-23 05:50:43,831: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2023-04-23 05:50:49,850: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 8.00 seconds... (4/100)

[2023-04-23 05:50:49,850: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 8.00 seconds... (4/100)

[2023-04-23 05:50:57,870: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 10.00 seconds... (5/100)

[2023-04-23 05:50:57,878: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 10.00 seconds... (5/100)

[2023-04-23 05:51:07,920: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 12.00 seconds... (6/100)

[2023-04-23 05:51:07,922: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 12.00 seconds... (6/100)

[2023-04-23 05:51:19,949: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 14.00 seconds... (7/100)

[2023-04-23 05:51:19,964: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 14.00 seconds... (7/100)

[2023-04-23 05:51:33,992: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 16.00 seconds... (8/100)

[2023-04-23 05:51:33,992: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 16.00 seconds... (8/100)

[2023-04-23 05:51:50,044: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 18.00 seconds... (9/100)

[2023-04-23 05:51:50,044: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 18.00 seconds... (9/100)

[2023-04-23 05:52:08,099: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 20.00 seconds... (10/100)

[2023-04-23 05:52:08,099: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 20.00 seconds... (10/100)

[2023-04-23 05:52:28,155: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 22.00 seconds... (11/100)

[2023-04-23 05:52:28,159: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 22.00 seconds... (11/100)

[2023-04-23 05:52:50,223: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 24.00 seconds... (12/100)

[2023-04-23 05:52:50,225: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 24.00 seconds... (12/100)

[2023-05-19 18:53:26,051: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

